compressionLevel: mixed

supportedArchitectures:
  os:
    - 'darwin'
    - 'linux'
    - 'win32'
  cpu:
    - 'x64'
    - 'arm64'
pnpEnableEsmLoader: true
enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  '@fastify/type-provider-typebox@*':
    dependencies:
      '@sinclair/typebox': '*'
  'ts-jest@*':
    peerDependencies:
      jest-util: '*'
