name: 'debug-container'

services:
  apache:
    image: httpd:latest
    container_name: apache
    restart: unless-stopped
    environment:
      - AAA='xia weoifoew'
      - BBA:"xia weiofhoewif"
      - file = debug-container/compose.yml wioefnew
      - 1sffile:debug-container/compose.yml oiewfjoew
      - ENABLED=true
      - DEBUG=false
      - MAX_RETRIES=5
      - TIMEOUT=3.5
    ports:
      - 8080:80
    volumes:
      - ./public-html:/usr/local/apache2/htdocs/
  portainer:
    image: portainer/portainer-ce:latest
    container_name: apache
    restart: unless-stopped
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./portainer_data:/data
