name: debug-container
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --admin-password
      - $$2y$$05$$wxahdaIgY6yjxyPjvSqyr.NeLhCOY/pWLXSJykVsfUGaRXnjq3etK
  gluesync-conductor:
    build: ../packages/gluesync-conductor
    container_name: gluesync-conductor
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - LOGGER_LEVEL=trace
      - GLUESYNC_LICENSE_FILE=/opt/gluesync/data/gs-license.dat
      - GLUESYNC_SECURITY_CONFIG=/opt/gluesync/data/security-config.json
      - GLUESYNC_MODULE_TAG=gluesync-conductor
      - HOST=0.0.0.0
      - PORT=1717
      - DOCKER_HOST=unix:///var/run/docker.sock
      - BASE_PATH=$PWD
      - ALLOWED_ORIGINS=http://localhost:8080,http://127.0.0.1:8080/,https://localhost:8080,https://127.0.0.1:8080/
    ports:
      - 5017:1717
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/opt/gluesync/data
      - ./gs-conf/gs-license.dat:/opt/gluesync/data/gs-license.dat
      - ./docker-compose.yml:/opt/gluesync-conductor/docker-compose.yml
    networks:
      - gluesync-network

  gluesync-core-hub:
    image: molo17/gluesync-core-hub:2.1.0.0.1f094fc18
    ports:
      - 1717:1717
    environment:
      - LOG_CONFIG_FILE=/opt/gluesync/data/logback.xml
    volumes:
      - ./gs-conf/gs-license.dat:/opt/gluesync/data/gs-license.dat
      - ./gs-conf/bootstrap-core-hub.json:/opt/gluesync/data/bootstrap-core-hub.json
      - ./gs-conf/security-config.json:/opt/gluesync/data/security-config.json
      - ./gs-conf/gluesync.com.jks:/opt/gluesync/data/gluesync.com.jks
    networks:
      - gluesync-network
networks:
  gluesync-network:
    driver: bridge
