services:
  gluesync-conductor:
    build: .
    container_name: gluesync-conductor
    image: gluesync-conductor
    restart: always
    ports:
      - 1717:1717
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
